# Generated by Django 5.2.17 on 2026-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creoledict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='examples_folded',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='definition',
            name='examples_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='definition',
            name='gloss_folded',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='definition',
            name='gloss_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='headword_folded',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='headword_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='text_folded',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='text_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
